"""Load skills from disk — `skill.yaml` only, never from prose.

The existing `providers/skills.py` walks a tree for `SKILL.md` and parses its
frontmatter. That stays, and it is correct for what it does: it discovers
upstream material and declares it `backend="none"`, which is an honest statement
that the file specifies a skill for a host agent rather than being one we can
run.

This loader is for the other path, the one ADR-0003 describes. A skill is
compiled from `skill.yaml`, and `SKILL.md` is read only to be attached to the
artifact as documentation. If a directory contains a `SKILL.md` and no
`skill.yaml`, this loader says so in a specific, actionable way rather than
silently ignoring the directory:

    CandidateSkillNeedsAdapter: no skill.yaml in .../foo; an upstream SKILL.md
    must be wrapped by a reviewed adapter before it can be compiled

That message is the whole point. The monthly Scout will meet thousands of
`SKILL.md`-only directories, and the failure mode to avoid is treating them as
loadable because they look like skills.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from .models import SkillSpec, spec_from_dict

__all__ = ["CandidateSkillNeedsAdapter", "LoadedSkill", "SkillLoadError",
           "entrypoint_module_path", "load_skill_dir", "load_skills",
           "skill_content_hash"]

SKILL_FILE = "skill.yaml"
DOC_FILE = "SKILL.md"


class SkillLoadError(ValueError):
    """A skill directory could not be loaded, with the reason."""


class CandidateSkillNeedsAdapter(SkillLoadError):
    """A directory holds `SKILL.md` but no `skill.yaml`.

    Distinct from a plain load error because the remedy is different and
    specific: write and review an adapter. The monthly Scout counts these
    separately — they are the candidate backlog, not failures.
    """


@dataclass(frozen=True, slots=True)
class LoadedSkill:
    """A skill and where it came from."""

    spec: SkillSpec
    directory: Path
    content_hash: str
    documentation: str = ""

    @property
    def id(self) -> str:
        return self.spec.id

    @property
    def composite_id(self) -> str:
        return self.spec.composite_id


def skill_content_hash(directory: Path, *, entrypoint: str = "") -> str:
    """SHA-256 over every file a skill is built from — manifest *and* code.

    Two sets of files, and missing the second is a hole rather than an
    inconvenience. The skill directory holds `skill.yaml`, but for a Python
    skill the implementation lives wherever `runtime.entrypoint` points — in this
    repository, `src/bioagent/skills/p0/`. A hash over the directory alone pins
    the *declaration* and leaves the behaviour editable, so an upstream (or
    local) change to the implementation would not move the pin. This was found
    by a test that edited a skill's implementation and watched the lockfile check
    pass when it should have failed.

    Excludes `SKILL.md`, which is documentation and cannot affect behaviour, and
    `__pycache__`, which is derived.
    """
    directory = Path(directory).resolve()
    digest = hashlib.sha256()
    for path in _hashed_files(directory, entrypoint):
        # The name that enters the digest is always relative to a *resolved*
        # base, never derived from how the caller spelled the path. An earlier
        # version used `relative_to(directory)` on the argument as given, so
        # `skills/tcm/x` and `/abs/skills/tcm/x` — the same tree — produced
        # different digests, and a lockfile generated by one caller failed to
        # verify under another. A pin that depends on the caller is not a pin.
        base = directory if _within(path, directory) else path.parent
        rel = path.relative_to(base).as_posix()
        digest.update(rel.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def _hashed_files(directory: Path, entrypoint: str) -> list[Path]:
    """The files that make up a skill: its directory, plus its implementation."""
    paths: list[Path] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file():
            continue
        if "__pycache__" in path.parts or path.name == DOC_FILE:
            continue
        if path.name.endswith((".pyc", ".pyo")):
            continue
        paths.append(path)

    module = entrypoint_module_path(entrypoint)
    if module is not None and module.is_file():
        paths.append(module)
        # For a package entrypoint (`pkg.module:fn`), the function lives in one
        # file but shares a package with the code it calls. Hashing the whole
        # package would be correct and would also mean every skill in a shared
        # package hashes identically, so the pin could not tell two of them
        # apart. Hash the entry module only, and say so: the guarantee is
        # "this file changed", not "nothing this file imports changed".
        #
        # The sibling glob that was here is deliberately gone — it made the set
        # depend on directory iteration and produced a different digest on
        # consecutive runs of the same tree.
        for sibling in sorted(module.parent.glob("*.py")):
            if (sibling.name in _ENTRYPOINT_COMPANIONS
                    and sibling.is_file() and "__pycache__" not in sibling.parts):
                paths.append(sibling)
    return sorted(set(paths))


#: Extra files hashed alongside an entrypoint module, by name. Empty by default:
#: a skill's behaviour should live in the module its manifest names. A skill that
#: genuinely needs more can list it here, at the cost of guaranteeing that
#: changing it moves every such skill's pin.
_ENTRYPOINT_COMPANIONS: frozenset[str] = frozenset()


def _within(path: Path, directory: Path) -> bool:
    try:
        path.relative_to(directory)
        return True
    except ValueError:
        return False


def entrypoint_module_path(entrypoint: str) -> Path | None:
    """Resolve a `module.path:callable` entrypoint to its source file, or None.

    Returns ``None`` rather than raising for an entrypoint this process cannot
    resolve — a skill whose implementation is installed elsewhere is hashed over
    its directory alone, and that is reported by the caller rather than silently
    producing a hash that looks complete.
    """
    if not entrypoint or ":" not in entrypoint:
        return None
    module_name = entrypoint.split(":", 1)[0].strip()
    if not module_name:
        return None
    try:
        import importlib.util
        spec = importlib.util.find_spec(module_name)
    except (ImportError, ValueError, ModuleNotFoundError):
        return None
    if spec is None or not spec.origin or spec.origin in ("built-in", "frozen"):
        return None
    return Path(spec.origin)


def load_skill_dir(directory: Path | str, *, require_implementation: bool = False
                   ) -> LoadedSkill:
    """Load one skill directory.

    ``require_implementation`` refuses a `python` skill whose entrypoint module
    is not present in the tree — the check that stops a manifest from pointing at
    code that does not exist, which would only surface at first invocation.
    """
    directory = Path(directory)
    if not directory.is_dir():
        raise SkillLoadError(f"{directory} is not a directory")

    manifest = directory / SKILL_FILE
    if not manifest.is_file():
        if (directory / DOC_FILE).is_file():
            raise CandidateSkillNeedsAdapter(
                f"no {SKILL_FILE} in {directory}; an upstream {DOC_FILE} must be "
                "wrapped by a reviewed adapter before it can be compiled")
        raise SkillLoadError(f"no {SKILL_FILE} or {DOC_FILE} in {directory}")

    import yaml  # imported here so the module loads without PyYAML present

    try:
        raw = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as exc:
        raise SkillLoadError(f"{manifest}: invalid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise SkillLoadError(f"{manifest}: expected a mapping at the top level")

    spec = spec_from_dict(raw, origin=str(directory))

    if require_implementation and spec.runtime.backend == "python":
        # Resolved through the import system, not relative to the skill
        # directory: an entrypoint is a dotted module path, and for every skill
        # in this repository the implementation lives in the package rather than
        # beside the manifest. Looking next to `skill.yaml` would have failed to
        # find code that is present and importable.
        resolved = entrypoint_module_path(spec.runtime.entrypoint)
        if resolved is None or not resolved.is_file():
            on_disk = directory / (spec.runtime.entrypoint.split(":", 1)[0]
                                   .replace(".", "/") + ".py")
            raise SkillLoadError(
                f"skill {spec.id!r} declares entrypoint {spec.runtime.entrypoint!r} "
                f"but it resolves to no source file (looked up as a module, and at "
                f"{on_disk})")

    doc = ""
    doc_path = directory / DOC_FILE
    if doc_path.is_file():
        doc = doc_path.read_text(encoding="utf-8", errors="replace")

    # The hash covers the manifest *and* the implementation the entrypoint
    # names, so it must be taken after the spec is parsed. Hashing the directory
    # alone would pin the declaration and leave the behaviour editable.
    digest = skill_content_hash(directory, entrypoint=spec.runtime.entrypoint)
    spec = _with_hash(spec, digest)
    return LoadedSkill(spec=spec, directory=directory, content_hash=digest,
                       documentation=doc)


def load_skills(root: Path | str, *, require_implementation: bool = False
                ) -> tuple[tuple[LoadedSkill, ...], tuple[tuple[Path, str], ...]]:
    """Load every skill under ``root``.

    Returns ``(loaded, refused)`` rather than raising on the first bad
    directory. A registry build must see the whole set: one malformed third-party
    skill should not stop the other nineteen from being audited, and the refused
    list is audit output in its own right.
    """
    root = Path(root)
    loaded: list[LoadedSkill] = []
    refused: list[tuple[Path, str]] = []
    if not root.is_dir():
        return (), ((root, f"{root} is not a directory"),)
    for directory in sorted(p for p in root.iterdir() if p.is_dir()):
        if not (directory / SKILL_FILE).is_file() and not (directory / DOC_FILE).is_file():
            continue
        try:
            loaded.append(load_skill_dir(directory,
                                         require_implementation=require_implementation))
        except SkillLoadError as exc:
            refused.append((directory, str(exc)))
    return tuple(loaded), tuple(refused)


def _with_hash(spec: SkillSpec, digest: str) -> SkillSpec:
    """A copy of ``spec`` carrying ``digest``. Frozen dataclasses have no setter."""
    from dataclasses import replace
    return replace(spec, content_hash=digest)
